- name: H
  description: hydrogen
  isotopes:
    - name: H1
      mass: 1.0078250
      abundance: 1.000
- name: C
  description: carbon
  isotopes:
    - name: C12
      mass: 12.0000000
      abundance: 98.930
    - name: C13
      mass: 13.0033548
      abundance: 1.070
- name: O
  description: oxygen
  isotopes:
    - name: O16
      mass: 15.9949146
      abundance: 0.998
    - name: O18
      mass: 17.9991596
      abundance: 0.002
- name: N
  description: nytrogen
  isotopes:
    - name: N14
      mass: 14.0030740
      abundance: 0.996
    - name: N15
      mass: 15.0001089
      abundance: 0.004
