name: ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD_TOKEN}}
        with:
          args: >
            -Dsonar.organization=${{secrets.SONARCLOUD_ORGANIZATION}}
            -Dsonar.projectKey=${{secrets.SONARCLOUD_PROJECT_KEY}}
